import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          CONRAD SOUNDSYSTEM
        </h1>

        <div className={styles.imageContainer}>
          <Image
            className={styles.image}
            src="/conrad.jpg"
            alt="picture of Conrad"
            width={450}
            height={450}
          />
        </div>

        <div className={styles.mixcloud}>
          <iframe width="100%" height="60" src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&mini=1&light=1&feed=%2Fconrad-soundsystem%2Fconrad-soundsystem-clubmusic-in-2020%2F" frameborder="0" />
          <iframe width="100%" height="60" src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&mini=1&light=1&feed=%2Fooradio%2F020%2F" frameborder="0" />
          <iframe width="100%" height="60" src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&mini=1&light=1&feed=%2Fconrad-soundsystem%2Fconrad-soundsystem-breaks-vinyl-mix%2F" frameborder="0" />
        </div>

      </main>
      <footer className={styles.footer}>
          <a href="mailto:general@conradsoundsystem.com">general@conradsoundsystem.com</a>
          <p>Conrad Soundsystem are Hugo Eno and David Lieffering</p>
      </footer>
    </div>
  )
}
